##
## List of required Debian packages
##
## (When making changes, always use the file `packages_debian.yml.in`)
##
---
- name: build-essential
  url:
  description: Informational list of build-essential packages
  version:
- name: cmake
  url:
  description: a cross-platform, open-source make system
  version:
- name: git-svn
  url:
  description: fast, scalable, distributed revision control system (svn interoperability)
  version:
- name: subversion
  url:
  description: Advanced version control system
  version:
- name: doxygen
  url:
  description: Documentation system for C, C++, Java, Python and other languages
  version:
- name: libboost-all-dev
  url:
  description: Boost C++ Libraries development files
  version:
- name: ruby1.8
  url:
  description: Interpreter of object-oriented scripting language Ruby 1.8
  version:
- name: ruby1.8-dev
  url:
  description: Header files for compiling extension modules for the Ruby 1.8
  version:
- name: rubygems
  url:
  description: package management framework for Ruby libraries/applications
  version:
- name: ri
  url:
  description: Ruby Interactive reference
  version:
- name: rake
  url:
  description: a ruby build program
  version:
- name: libmysql-ruby1.8
  url:
  description: MySQL module for Ruby 1.8
  version:
- name: libtermios-ruby1.8
  url:
  description:
  version:
- name: librmagick-ruby1.8
  url:
  description:
  version:
- name: libruby1.8
  url:
  description: Libraries necessary to run Ruby 1.8
  version:
- name: mysql-server
  url:
  description: MySQL database server
  version:
- name: mysql-client
  url:
  description: MySQL database client
  version:
- name: libmysqlclient-dev
  url:
  description:
  version:
- name: apache2
  url:
  description:
  version:
- name: libapache2-mod-ruby
  url:
  description:
  version:
- name: libapache2-mod-proxy-html
  url:
  description:
  version:
- name: libxml2-dev
  url:
  description:
  version:
- name: libmagic-dev
  url:
  description: File type determination library using "magic" numbers
  version:
- name: libmagickwand-dev
  url:
  description: image manipulation library - development files
  version:
- name: zlib1g-dev
  url:
  description: compression library - development
  version:
