##
## List of required MacPorts packages
##
---
- name: cmake
  url:
  description: A cross-platform, open-source make system
  version:
- name: doxygen
  url:
  description:
  version:
- name: libxml2
  url:
  description: XML C library developed for the Gnome project
  version:
- name: mod_ruby
  url:
  description:
  version:
- name: mysql5-devel
  url:
  description: Multithreaded SQL database server, development files
  version:
- name: rb-rubygems
  url:
  description:
  version:
- name: ruby
  url:
  description: Powerful and clean object-oriented scripting language
  version:
