##
## List of required MacPorts packages
##
---
- name: ruby
  url: https://apps.fedoraproject.org/packages/ruby
  description: An interpreter of object-oriented scripting language
  version:
- name: rubygems
  url: https://apps.fedoraproject.org/packages/rubygems
  description: The Ruby standard for packaging ruby libraries
  version:
- name: rubygem-rails
  url: https://apps.fedoraproject.org/packages/rubygem-rails
  description: Web-application framework
  version:
- name: rdoc
  url:
  description:
  version:
- name: ri
  url:
  description:
  version:
- name: irb
  url:
  description:
  version:
- name: eruby
  url:
  description:
  version:
- name: git-svn
  url:
  description: Git tools for importing Subversion repositories
  version:
- name: doxygen
  url: https://apps.fedoraproject.org/packages/doxygen
  description: A documentation system for C/C++
  version:
- name: libxml2-devel
  url:
  description:
  version:
- name: mysql-server
  url:
  description:
  version:
- name: mysql-client
  url:
  description:
  version:
- name: mysql-devel
  url:
  description:
  version:
- name: apache2
  url:
  description:
  version:
- name: postfix
  url:
  description:
  version:
- name: subversion
  url:
  description:
  version:
- name: subversion-tools
  url:
  description:
  version:
- name: libapache2-svn
  url:
  description:
  version:
- name: ImageMagick
  url: https://apps.fedoraproject.org/packages/ImageMagick
  description: An X application for displaying and manipulating images
  version:
- name: ImageMagick-devel
  url: https://apps.fedoraproject.org/packages/ImageMagick-devel
  description: Library links and header files for ImageMagick app development
  version:
