##
## List of required MacPorts packages
##
## - name       : Name of the package, as used when running e.g. `gem install <name>`
## - version    : Version constraints for the package.
## - homepage   : Project website/homepage.
## - descripion : A short description of the package.
##
---
- name: gcc
  version:
  homepage:
  description: Various compilers (C, C++, Objective-C, Java, ...)
- name: gcc-c++
  version:
  homepage:
  description: C++ support for GCC
- name: boost-devel
  version:
  homepage:
  description: The Boost C++ headers and shared development libraries
- name: ruby
  version:
  homepage: https://apps.fedoraproject.org/packages/ruby
  description: An interpreter of object-oriented scripting language
- name: rubygems
  version:
  homepage: https://apps.fedoraproject.org/packages/rubygems
  description: The Ruby standard for packaging ruby libraries
- name: rubygem-rails
  version:
  homepage: https://apps.fedoraproject.org/packages/rubygem-rails
  description: Web-application framework
- name: rubygem-rdoc
  version:
  homepage:
  description: RDoc produces HTML and command-line documentation for Ruby projects
- name: ri
  version:
  homepage:
  description:
  version:
- name: ruby-irb
  version:
  homepage:
  description: The Interactive Ruby
- name: eruby
  version:
  homepage:
  description: An interpreter of embedded Ruby language 
- name: git-svn
  version:
  homepage:
  description: Git tools for importing Subversion repositories
- name: doxygen
  version:
  homepage: https://apps.fedoraproject.org/packages/doxygen
  description: A documentation system for C/C++
- name: libxml2-devel
  version:
  homepage:
  description:
- name: mysql-server
  version:
  homepage:
  description:
- name: mysql-client
  version:
  homepage:
  description:
- name: mysql-devel
  version:
  homepage:
  description:
- name: apache2
  version:
  homepage:
  description:
- name: postfix
  version:
  homepage:
  description:
- name: subversion
  version:
  homepage:
  description: A Modern Concurrent Version Control System
- name: subversion-tools
  version:
  homepage:
  description: Supplementary tools for Subversion
- name: mod_dav_svn
  version:
  homepage:
  description: Apache httpd module for Subversion server
- name: ImageMagick
  version:
  homepage: https://apps.fedoraproject.org/packages/ImageMagick
  description: An X application for displaying and manipulating images
- name: ImageMagick-devel
  version:
  homepage: https://apps.fedoraproject.org/packages/ImageMagick-devel
  description: Library links and header files for ImageMagick app development
