##
## List of required MacPorts packages
##
---
- name: cmake
  version:
  homepage:
  description: A cross-platform, open-source make system
- name: doxygen
  version:
  homepage:
  description:
- name: libxml2
  version:
  homepage:
  description: XML C library developed for the Gnome project
- name: mod_ruby
  version:
  homepage:
  description:
- name: mysql5-devel
  version:
  homepage:
  description: Multithreaded SQL database server, development files
- name: rb-rspec
  version:
  homepage:
  description: Behaviour Driven Development framework for Ruby
- name: rb-rubygems
  version:
  homepage:
  description:
- name: ruby
  version:
  homepage:
  description: Powerful and clean object-oriented scripting language
- name: yaml-cpp
  version:
  homepage: http://code.google.com/p/yaml-cpp
  description: yaml-cpp is a YAML parser and emitter in C++ written around the YAML 1.2 spec
