##
## List of required Ruby gems.
##
---
- name: apache_image_resizer
  url: https://github.com/prometheus-ev/apache_image_resizer
  description: Apache module providing image resizing functionality.
  version: '>= 0.0.7'
- name: apache_secure_download
  url: https://github.com/prometheus-ev/apache_secure_download
  description: Apache module providing secure downloading functionality.
  version: '>= 0.2.1'
- name: ar_mailer
  url: https://rubygems.org/gems/ar_mailer
  description: A two-phase delivery agent for ActionMailer.
  version:
- name: blackwinter-gnuplot
  url: https://rubygems.org/gems/blackwinter-gnuplot
  description: Utility library to aid in interacting with Gnuplot.
  version:
- name: blackwinter-ipaddress
  url: https://rubygems.org/gems/blackwinter-ipaddress
  description: A library designed to make manipulation of IPv4 and IPv6 addresses both powerful and simple.
  version: '= 0.8.0'
- name: capistrano
  url: https://rubygems.org/gems/capistrano
  description: A utility and framework for executing commands in parallel on multiple remote machines, via SSH.
  version:
- name: exifr
  url: https://rubygems.org/gems/exifr
  description: EXIF Reader is a module to read EXIF from JPEG images.
  version:
- name: fastercsv
  url: https://rubygems.org/gems/fastercsv
  description: Intended as a complete replacement to the CSV standard library.
  version:
- name: ferret
  url: https://rubygems.org/gems/ferret
  description: A super fast, highly configurable search library.
  version: '= 0.11.8.1'
- name: gruff
  url: https://rubygems.org/gems/gruff
  description: Beautiful graphs for one or multiple datasets.
  version:
- name: highline
  url: http://highline.rubyforge.org
  description: A high-level IO library that provides validation, type conversion, and more for command-line interfaces.
  version:
- name: hpricot
  url: http://github.com/why/hpricot
  description: A swift, liberal HTML parser with a fantastic library.
  version:
- name: ipaddress
  url: https://rubygems.org/gems/ipaddress
  description: A library designed to make manipulation \ of IPv4 and IPv6 addresses both powerful and simple.
  version:
- name: jekyll
  url: https://github.com/mojombo/jekyll
  description: A simple, blog aware, static site generator.
  version:
- name: jekyll-localization
  url: https://github.com/prometheus-ev/jekyll-localization
  description: Jekyll plugin that adds localization features to the rendering engine.
  version:
- name: jekyll-pagination
  url: https://github.com/prometheus-ev/jekyll-pagination
  description: Jekyll plugin to extend the pagination generator.
  version:
- name: jekyll-tagging
  url: https://github.com/prometheus-ev/jekyll-tagging
  description: Jekyll plugin to automatically generate a tag cloud and tag pages.
  version:
- name: json
  url: http://flori.github.com/json
  description: JSON implementation for Ruby.
  version:
- name: libxml-ext
  url: https://github.com/prometheus-ev/libxml-ext
  description: LibXML Ruby extensions.
  version:
- name: libxml-ruby
  url: http://xml4r.github.com/libxml-ruby
  description: Ruby language bindings for the GNOME Libxml2 XML toolkit.
  version: '>= 1.1.3'
- name: lockfile
  url: https://github.com/ahoward/lockfile
  description: A Ruby library for creating NFS safe lockfiles.
  version:
- name: mail
  url: https://rubygems.org/gems/mail
  description: A really Ruby Mail handler.
  version:
- name: mime-types
  url: https://rubygems.org/gems/mime-types
  description: Identification of a file's likely MIME content type.
  version:
- name: mongrel
  url: https://rubygems.org/gems/mongrel
  description: A small fast HTTP library and server that runs Rails, Camping, Nitro and Iowa apps.
  version:
- name: mongrel_cluster
  url: https://rubygems.org/gems/mongrel_cluster
  description: Mongrel plugin that provides commands and Capistrano tasks for managing multiple Mongrel processes.
  version:
- name: mysql
  url: http://www.tmtm.org/en/mysql/ruby
  description: MySQL API module for Ruby.
  version:
- name: oauth
  url: https://rubygems.org/gems/oauth
  description: OAuth Core Ruby implementation.
  version:
- name: pbkdf2
  url: https://rubygems.org/gems/pbkdf2
  description: Password Based Key Derivation Function 2 (PBKDF2) for Ruby.
  version:
- name: pdf-reader
  url: https://rubygems.org/gems/pdf-reader
  description: A PDF parser conforming as much as possible to the PDF specification from Adobe.
  version:
- name: piston
  url: http://piston.rubyforge.org
  description: Piston makes it easy to merge vendor branches into your own repository.
  version:
- name: rake
  url: http://docs.rubyrake.org
  description: A Make-like program implemented in Ruby. Tasks and dependencies arespecified in standard Ruby syntax.
  version:
- name: redcarpet
  url: https://rubygems.org/gems/redcarpet
  description: A fast, safe and extensible Markdown to (X)HTML parser.
  version:
- name: ruby-backports
  url: https://github.com/blackwinter/ruby-backports
  description: Backports of newer Ruby features to older versions.
  version:
- name: ruby-debug
  url: https://github.com/ruby-debug
  description: A generic command line interface for ruby-debug.
  version:
- name: ruby-filemagic
  url: https://github.com/prometheus-ev/ruby-filemagic
  description: Ruby bindings to the magic(4) library, revised.
  version:
- name: ruby-hmac
  url: http://ruby-hmac.rubyforge.org
  description: Common interface to HMAC functionality.
  version:
- name: ruby-nuggets
  url: https://github.com/prometheus-ev/ruby-nuggets
  description: Some extensions to the Ruby programming language
  version: '>= 0.8.9'
- name: unicode
  url: https://rubygems.org/gems/unicode
  description: Unicode normalization library.
  version: '>= 0.1.1'
- name: wadl
  url: https://github.com/prometheus-ev/wadl
  description: Ruby client for the Web Application Description Language.
  version:
- name: yard
  url: http://yardoc.org
  description: A documentation generation tool for the Ruby programming language.
  version:
